import { writable } from 'svelte/store';
import { base } from '$app/paths';
import builtPages from '$lib/archiePages.json';

export const isAuthenticated = writable(false);

async function fetchArchiePages() {
	if (typeof window === 'undefined') {
		return {};
	}

	// In production, use the content generated by copy-archiePages.cjs during the build.
	// This keeps the deployed portfolio aligned with the application-specific narrative
	// instead of reloading the untouched static/archiePages.json at runtime.
	if (import.meta.env.PROD) {
		return builtPages;
	}

	// Development keeps the live JSON workflow used by the admin/editor.
	const url = `${base}/archiePages.json?_=${Date.now()}`;
	const res = await fetch(url);
	if (!res.ok) return {};
	return res.json();
}

function createArchiePagesStore() {
	const { subscribe, set, update } = writable({});

	if (typeof window !== 'undefined') {
		fetchArchiePages()
			.then((data) => set(data))
			.catch(() => {});
	}

	return {
		subscribe,
		set: (value) => set(value),
		update: (fn) => update((current) => fn(current)),
		reload: async () => {
			if (typeof window !== 'undefined') {
				try {
					const data = await fetchArchiePages();
					set(data);
					return data;
				} catch (error) {
					console.error('Failed to reload ArchiePages:', error);
					throw error;
				}
			}
		}
	};
}

export const archiePages = createArchiePagesStore();
