name: Deploy to GitHub Pages

on:
  push:
    branches: [main, master]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Clean npm cache and lockfile (workaround Rollup bug)
        run: rm -rf node_modules package-lock.json

      - name: Install dependencies (workaround Rollup bug)
        run: npm install --legacy-peer-deps

      - name: Install sharp for image optimization
        run: npm install sharp --no-save

      - name: Generate WebP/AVIF images
        run: node scripts/optimize-images.cjs

      - name: Build static site
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          publish_branch: gh-pages
          force_orphan: true
